# AirBnB NY Locations Data Case Study

In this final project, you task will be to take the data provided and find evidance to answer the following questions.

1. Which hosts are the busiest and why?
2. How many neighborhood groups are available and which shows up the most?
3. Are private rooms the most popular in manhattan?
4. Which hosts are the busiest and based on their reviews?
5. Which neighorhood group has the highest average price?
6. Which neighborhood group has the highest total price?
7. Which top 5 hosts have the highest total price?
8. Who currently has no (zero) availability with a review count of 100 or more?
9. What host has the highest total of prices and where are they located?
10. When did Danielle from Queens last receive a review?

You will be given **4 hours** to complete this assignment. 
**Be Advised** I will go dark for this intire assignment time period. That said, any questions that you would like to ask about the data, or the project **MUST** be asked before the time starts. Once the time has started, I can no longer give information.

This is to similate what you will face when you are out in the wild. 

Happy Coding!

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

C:\Users\todds\anaconda3\lib\site-packages\numpy\core\getlimits.py:172: RuntimeWarning: divide by zero encountered in exp2
  eps=exp2(ld(-112)),
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\getlimits.py:51: RuntimeWarning: divide by zero encountered in log10
  self.precision = int(-log10(self.eps))
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\getlimits.py:52: RuntimeWarning: divide by zero encountered in power
  self.resolution = float_to_float(float_conv(10) ** (-self.precision))
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\getlimits.py:184: RuntimeWarning: divide by zero encountered in exp2
  epsneg_f80 = exp2(ld(-64))
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\getlimits.py:185: RuntimeWarning: divide by zero encountered in exp2
  tiny_f80 = exp2(ld(-16382))
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\getlimits.py:199: RuntimeWarning: divide by zero encountered in exp2
  eps=exp2(ld(-63)),
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\getlimits.py:211: RuntimeWarning: divide by zero encountered in nextafter
  huge_dd = (umath.nextafter(ld(inf), ld(0))
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\getlimits.py:224: RuntimeWarning: divide by zero encountered in exp2
  eps=exp2(ld(-105)),
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\getlimits.py:225: RuntimeWarning: divide by zero encountered in exp2
  epsneg= exp2(ld(-106)),
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\getlimits.py:227: RuntimeWarning: divide by zero encountered in exp2
  tiny=exp2(ld(-1022)))
C:\Users\todds\anaconda3\lib\site-packages\numpy\__init__.py:343: RuntimeWarning: divide by zero encountered in subtract
  if not abs(x.dot(x) - 2.0) < 1e-5:
C:\Users\todds\anaconda3\lib\site-packages\numpy\__init__.py:343: RuntimeWarning: divide by zero encountered in absolute
  if not abs(x.dot(x) - 2.0) < 1e-5:
<frozen importlib._bootstrap>:219: RuntimeWarning: divide by zero encountered in add
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\function_base.py:127: RuntimeWarning: divide by zero encountered in multiply
  start = asanyarray(start) * 1.0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\function_base.py:128: RuntimeWarning: divide by zero encountered in multiply
  stop  = asanyarray(stop)  * 1.0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\function_base.py:134: RuntimeWarning: divide by zero encountered in double_scalars
  delta = stop - start
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\function_base.py:141: RuntimeWarning: divide by zero encountered in double_scalars
  step = delta / div
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\function_base.py:151: RuntimeWarning: divide by zero encountered in multiply
  y *= step
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\function_base.py:161: RuntimeWarning: divide by zero encountered in add
  y += start
C:\Users\todds\anaconda3\lib\site-packages\matplotlib\colors.py:989: RuntimeWarning: divide by zero encountered in double_scalars
  [(1.0 - x, y1, y0) for x, y0, y1 in reversed(data)])
C:\Users\todds\anaconda3\lib\site-packages\matplotlib\markers.py:796: RuntimeWarning: divide by zero encountered in true_divide
  np.array([(-1, -3), (+1, -3), (+1, -1), (+3, -1), (+3, +1), (+1, +1),
C:\Users\todds\anaconda3\lib\site-packages\matplotlib\markers.py:800: RuntimeWarning: divide by zero encountered in true_divide
  np.array([(+3, 0), (+3, +1), (+1, +1), (+1, +3),
C:\Users\todds\anaconda3\lib\site-packages\matplotlib\markers.py:820: RuntimeWarning: divide by zero encountered in true_divide
  np.array([(-1, -2), (0, -1), (+1, -2), (+2, -1), (+1, 0), (+2, +1),
C:\Users\todds\anaconda3\lib\site-packages\matplotlib\markers.py:825: RuntimeWarning: divide by zero encountered in true_divide
  np.array([(+1, 0), (+2, +1), (+1, +2), (0, +1),
C:\Users\todds\anaconda3\lib\site-packages\matplotlib\tri\triinterpolate.py:668: RuntimeWarning: divide by zero encountered in true_divide
  gauss_w = np.ones([9], dtype=np.float64) / 9.

In [15]:
air_bnb = pd.read_csv('AB_NYC_2019.csv')
air_bnb.head()

C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:254: RuntimeWarning: divide by zero encountered in isnan
  result = np.isnan(values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1498: RuntimeWarning: divide by zero encountered in absolute
  abs_vals = np.abs(self.values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1502: RuntimeWarning: divide by zero encountered in greater
  has_large_values = (abs_vals > 1e6).any()
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in less
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in greater
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in bitwise_and
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:254: RuntimeWarning: divide by zero encountered in isnan
  result = np.isnan(values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1498: RuntimeWarning: divide by zero encountered in absolute
  abs_vals = np.abs(self.values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1502: RuntimeWarning: divide by zero encountered in greater
  has_large_values = (abs_vals > 1e6).any()
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in less
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in greater
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in bitwise_and
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [19]:
# How many neighborhood groups are available and which shows up the most?
neighbourhood = air_bnb.groupby('neighbourhood_group')['neighbourhood'].count().reset_index()
neighbourhood

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\groupby\generic.py:844: RuntimeWarning: divide by zero encountered in not_equal
  mask = (ids != -1) & ~isna(val)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\groupby\generic.py:844: RuntimeWarning: divide by zero encountered in invert
  mask = (ids != -1) & ~isna(val)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\groupby\generic.py:844: RuntimeWarning: divide by zero encountered in bitwise_and
  mask = (ids != -1) & ~isna(val)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\numeric.py:2453: RuntimeWarning: divide by zero encountered in equal
  return bool(asarray(a1 == a2).all())
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:62: RuntimeWarning: divide by zero encountered in reduce
  return umr_all(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred

  neighbourhood_group  neighbourhood
0               Bronx           1091
1            Brooklyn          20104
2           Manhattan          21661
3              Queens           5666
4       Staten Island            373

In [50]:
# Are private rooms the most popular in manhattan?

# first filter our data_frame - aka only manhattan
# then groupby
# then aggregate (are we summing, counting, averaging)
# then select specific columns

rooms = air_bnb[air_bnb['neighbourhood_group'] == 'Manhattan'].groupby(['room_type']).count()[['id']]
rooms

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:284: RuntimeWarning: divide by zero encountered in less
  mask = indices < 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in greater_equal
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in less
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:290: RuntimeWarning: divide by zero encountered in bitwise_or
  mask = (indices >= n) | (indices < 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\array_algos\take.py:534: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexes\base.py:6015: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:795: RuntimeWarning: divide by zero encountered in int_scalars
  max_len = max(len(mgr_locs), taker.max() + 1)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\algorithms.py:769: RuntimeWarning: divide by zero encountered in equal
  code_is_na = codes == na_sentinel
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\groupby\generic.py:1731: RuntimeWarning: divide by zero encountered in not_equal
  mask = ids != -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\blocks.py:483: RuntimeWarning: divide by zero encountered in int_scalars
  nb = self.make_block(vals, BlockPlacement(ref_loc))
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexing.py:1357: RuntimeWarning: divide by zero encountered in less
  missing_mask = indexer < 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:47: RuntimeWarning: divide by zero encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)

                    id
room_type
Entire home/apt  13199
Private room      7982
Shared room        480

In [67]:
# Which hosts are the busiest and based on their reviews?

num_reviews = air_bnb.groupby('host_name')['number_of_reviews'].count().reset_index().sort_values('number_of_reviews', ascending=False)
num_reviews

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\algorithms.py:769: RuntimeWarning: divide by zero encountered in equal
  code_is_na = codes == na_sentinel
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\groupby\generic.py:844: RuntimeWarning: divide by zero encountered in not_equal
  mask = (ids != -1) & ~isna(val)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:254: RuntimeWarning: divide by zero encountered in isnan
  result = np.isnan(values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\groupby\generic.py:844: RuntimeWarning: divide by zero encountered in invert
  mask = (ids != -1) & ~isna(val)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\groupby\generic.py:844: RuntimeWarning: divide by zero encountered in bitwise_and
  mask = (ids != -1) & ~isna(val)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\numeric.py:2453: RuntimeWarning: divide by zero encountered in equal
  return bool(asarray(a1 == a2).all())
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:62: RuntimeWarning: divide by zero encountered in reduce
  return umr_all(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:396: RuntimeWarning: divide by zero encountered in invert
  non_nans = items[~mask]
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:397: RuntimeWarning: divide by zero encountered in invert
  non_nan_idx = idx[~mask]
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:284: RuntimeWarning: divide by zero encountered in less
  mask = indices < 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\array_algos\take.py:534: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:62: RuntimeWarning: divide by zero encountered in reduce
  return umr_all(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:62: RuntimeWarning: divide by zero encountered in reduce
  return umr_all(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred

          host_name  number_of_reviews
7135        Michael                417
2376          David                403
9781   Sonder (NYC)                327
4989           John                294
314            Alex                279
...             ...                ...
4804        Jerbean                  1
4803         Jerald                  1
4802      Jeonghoon                  1
4800           Jeny                  1
11451            현선                  1

[11452 rows x 2 columns]

In [68]:
#Which neighorhood group has the highest average price?

hprice = air_bnb.groupby('neighbourhood_group')['price'].mean().reset_index().sort_values('price', ascending=False)
hprice

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\algorithms.py:769: RuntimeWarning: divide by zero encountered in equal
  code_is_na = codes == na_sentinel
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:254: RuntimeWarning: divide by zero encountered in isnan
  result = np.isnan(values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:396: RuntimeWarning: divide by zero encountered in invert
  non_nans = items[~mask]
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:397: RuntimeWarning: divide by zero encountered in invert
  non_nan_idx = idx[~mask]
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:284: RuntimeWarning: divide by zero encountered in less
  mask = indices < 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:254: RuntimeWarning: divide by zero encountered in isnan
  result = np.isnan(values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1498: RuntimeWarning: divide by zero encountered in absolute
  abs_vals = np.abs(self.values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1502: RuntimeWarning: divide by zero encountered in greater
  has_large_values = (abs_vals > 1e6).any()
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in less
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in greater
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in bitwise_and
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:358: RuntimeWarning: divide by zero encountered in invert
  return ~res
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:87: RuntimeWarning: divide by zero encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1323: RuntimeWarning: divide by zero encountered in bitwise_and
  inferred
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\dtypes\missing.py:254: RuntimeWarning: divide by zero encountered in isnan
  result = np.isnan(values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1498: RuntimeWarning: divide by zero encountered in absolute
  abs_vals = np.abs(self.values)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1502: RuntimeWarning: divide by zero encountered in greater
  has_large_values = (abs_vals > 1e6).any()
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in less
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in greater
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\format.py:1504: RuntimeWarning: divide by zero encountered in bitwise_and
  (abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)

  neighbourhood_group       price
2           Manhattan  196.875814
1            Brooklyn  124.383207
4       Staten Island  114.812332
3              Queens   99.517649
0               Bronx   87.496792

In [73]:
# Which neighbor hood group has the highest total price?

highprice = air_bnb.groupby('price').count().sort_values('price', ascending=False)
highprice

C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexes\base.py:6015: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:795: RuntimeWarning: divide by zero encountered in int_scalars
  max_len = max(len(mgr_locs), taker.max() + 1)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\algorithms.py:769: RuntimeWarning: divide by zero encountered in equal
  code_is_na = codes == na_sentinel
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\groupby\generic.py:1731: RuntimeWarning: divide by zero encountered in not_equal
  mask = ids != -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\blocks.py:483: RuntimeWarning: divide by zero encountered in int_scalars
  nb = self.make_block(vals, BlockPlacement(ref_loc))
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:396: RuntimeWarning: divide by zero encountered in invert
  non_nans = items[~mask]
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\sorting.py:397: RuntimeWarning: divide by zero encountered in invert
  non_nan_idx = idx[~mask]
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\indexers.py:284: RuntimeWarning: divide by zero encountered in less
  mask = indices < 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\array_algos\take.py:534: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\concat.py:339: RuntimeWarning: divide by zero encountered in equal
  if (indexer == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\array_algos\take.py:534: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:39: RuntimeWarning: divide by zero encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:127: RuntimeWarning: divide by zero encountered in long_scalars
  np.array([self.adj.len(x) for x in idx]).max() + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:126: RuntimeWarning: divide by zero encountered in long_scalars
  lwidth -= (  # type: ignore[assignment,arg-type]
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:204: RuntimeWarning: divide by zero encountered in long_scalars
  w_adjoined = w + adjoin_width
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:205: RuntimeWarning: divide by zero encountered in long_scalars
  curr_width += w_adjoined
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:209: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 2 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\io\formats\string.py:207: RuntimeWarning: divide by zero encountered in long_scalars
  wrap = curr_width + 1 > line_width and i > 0
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\managers.py:238: RuntimeWarning: divide by zero encountered in equal
  if (new_blknos == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\numpy\core\_methods.py:56: RuntimeWarning: divide by zero encountered in reduce
  return umr_any(a, axis, dtype, out, keepdims)
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\internals\concat.py:339: RuntimeWarning: divide by zero encountered in equal
  if (indexer == -1).any():
C:\Users\todds\anaconda3\lib\site-packages\pandas\core\array_algos\take.py:534: RuntimeWarning: divide by zero encountered in equal
  mask = indexer == -1

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
price,,,,,,,,,,,,,,,
10000,3,3,3,3,3,3,3,3,3,3,3,2,2,3,3
9999,3,3,3,3,3,3,3,3,3,3,3,2,2,3,3
8500,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
8000,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
7703,1,1,1,1,1,1,1,1,1,1,1,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
12,4,4,4,4,4,4,4,4,4,4,4,1,1,4,4
11,3,3,3,3,3,3,3,3,3,3,3,1,1,3,3
10,17,17,17,17,17,17,17,17,17,17,17,12,12,17,17
0,11,11,11,11,11,11,11,11,11,11,11,10,10,11,11

In [ ]:
#Which top 5 hosts have the highest total price?

In [90]:
# Who currently has no (zero) availability with a review count of 100 or more?
#noavail = air_bnb.groupby('host_name', 'availability_365')['number_of_reviews'].sum(>100).reset_index().sort_values('availability_365', ascending=True)
#noavail
#noavail = air_bnb[air_bnb.number_of_reviews>= 100].groupby(['availability_365']).count()('availability_365', ascending=False)
#noavail

noavail = air_bnb.groupby('host_name', 'availability_365')['number_of_reviews'].sum().reset_index()
noavail = noavail[noavail['availability_365'] >= 100].sort_values('availability_365', ascending=True)
noavail

ValueError: No axis named availability_365 for object type DataFrame

In [ ]:
# What host has the highest total of prices and where are they located?

In [ ]:
# When did Danielle from Queens last receive a review?

## Further Questions

1. Which host has the most listings?

2. How many listings have completely open availability?

3. What room_types have the highest review numbers?

# Final Conclusion

In this cell, write your final conclusion for each of the questions asked.

Also, if you uncovered some more details that were not asked above, please discribe them here.

-- Add your conclusion --